### ISSUE TITLE
Github site

### ISSUE THREAD

**Issue by xji3** [muddin21/muddin21#1]
You might want to change the repository to `muddin21.github.io` so that it becomes a site.  Here is a tutorial: https://xji3.github.io/Tutorial/

**Comment by muddin21** [comment]
I appreciate your recommendation. I already created a webpage using Google Sites ([http://www.math.tulane.edu/~muddin1](http://www.math.tulane.edu/~muddin1)). However, I'll try to implement or transfer to GitHub pages(if possible) later.
